import { Noto_Sans_JP } from "next/font/google";
import Header from "./Header";
import "./globals.css";

const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});

export const metadata = {
  title: "Next.js Awesome Note App",
  description: "Generated by create next app",
};

/**
 * ルートレイアウトコンポーネント
 * @param children Reactコンポーネント
 * @return {JSX.Element} ルートレイアウトコンポーネントのJSX要素
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const NotoSansJP = Noto_Sans_JP({
    weight: ["400", "700"],
    subsets: ["latin"],
    preload: true,
  });

  return (
    <html lang="ja">
      <body className={NotoSansJP.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
